# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Project\calculating-correction-procedure/ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

import MainWindow_rc
#import time
import Tools


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow: QtWidgets.QMainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.setFixedSize(self.width(), self.height())
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Main = QtWidgets.QFrame(self.centralwidget)
        self.Main.setGeometry(QtCore.QRect(0, 0, 600, 500))
        self.Main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main.setObjectName("Main")
        self.Author = QtWidgets.QLabel(self.Main)
        self.Author.setGeometry(QtCore.QRect(10, 480, 100, 10))
        self.Author.setObjectName("Author")
        self.Version = QtWidgets.QLabel(self.Main)
        self.Version.setGeometry(QtCore.QRect(10, 460, 40, 10))
        self.Version.setObjectName("Version")
        self.Title = QtWidgets.QLabel(self.Main)
        self.Title.setGeometry(QtCore.QRect(160, 60, 280, 60))
        font = QtGui.QFont()
        font.setPointSize(34)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.OpenImage = QtWidgets.QPushButton(self.Main)
        self.OpenImage.setGeometry(QtCore.QRect(150, 350, 100, 40))
        self.OpenImage.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.OpenImage.setObjectName("OpenImage")
        self.OpenImage.clicked.connect(self.openPhotoEvent)
        self.Exit = QtWidgets.QPushButton(self.Main)
        self.Exit.setGeometry(QtCore.QRect(350, 350, 100, 40))
        self.Exit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Exit.setObjectName("Exit")
        self.Exit.clicked.connect(QtCore.QCoreApplication.instance().quit)
        self.label = QtWidgets.QLabel(self.Main)
        self.label.setGeometry(QtCore.QRect(100, 120, 400, 200))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Wait = QtWidgets.QFrame(self.centralwidget)
        self.Wait.setGeometry(QtCore.QRect(0, 0, 600, 500))
        self.Wait.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Wait.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Wait.setObjectName("Wait")
        self.WaitText = QtWidgets.QLabel(self.Wait)
        self.WaitText.setGeometry(QtCore.QRect(300, 200, 290, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.WaitText.setFont(font)
        self.WaitText.setObjectName("WaitText")
        self.WaitIcon = QtWidgets.QLabel(self.Wait)
        self.WaitIcon.setGeometry(QtCore.QRect(100, 150, 200, 200))
        self.WaitIcon.setText("")
        self.WaitGif = QtGui.QMovie(":/WaitIcon/loading.gif")
        self.WaitIcon.setMovie(self.WaitGif)
        self.WaitGif.start()
        self.WaitIcon.setObjectName("WaitIcon")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.initClient()
        self.showMain()

    def showMain(self):
        self.Main.setVisible(True)
        self.Wait.setVisible(False)

    def showWait(self):
        self.Main.setVisible(False)
        self.Wait.setVisible(True)

    def openPhotoEvent(self):
        temp = Tools.getPhoto()
        if temp:
            self.base64_photo = temp
            del temp
        else:
            del temp
            return 0
        self.showWait()
        self.access_token = Tools.getAccessToken(
            self.client_id, self.client_secret)
        # time.sleep(10)
        if self.access_token == False:
            self.showMain()
            return 0
        self.result = Tools.getDistinguishResult(
            self.base64_photo, self.access_token)
        del self.base64_photo, self.access_token
        if self.result == False:
            self.showMain()
            return 0

        self.result = Tools.resultParser(self.result)
        if self.result == False:
            self.showMain()
            return 0
        Tools.saveResult(self.result)
        self.showMain()

    def initClient(self):
        self.client_id = "mvWgpUChDGa0ba9XyNgV2k9G"
        self.client_secret = "xyHmCRUO6lCtOQBjMaWsq6KCFgkCK6CZ"

    def retranslateUi(self, MainWindow: QtWidgets.QMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "口算批改程序"))
        self.Author.setText(_translate("MainWindow", "作者:ChenHaoYan"))
        self.Version.setText(_translate("MainWindow", "V1.0.0"))
        self.Title.setText(_translate("MainWindow", "口算批改程序"))
        self.OpenImage.setText(_translate("MainWindow", "打开图片"))
        self.Exit.setText(_translate("MainWindow", "退出"))
        self.label.setText(_translate("MainWindow", "请点击打开图片按钮以上传图片。"))
        self.WaitText.setText(_translate("MainWindow", "正在识别中,请等一下。"))
