# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Project\calculating-correction-procedure\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Main = QtWidgets.QFrame(self.centralwidget)
        self.Main.setGeometry(QtCore.QRect(0, 0, 600, 500))
        self.Main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main.setObjectName("Main")
        self.Author = QtWidgets.QLabel(self.Main)
        self.Author.setGeometry(QtCore.QRect(10, 490, 100, 10))
        self.Author.setObjectName("Author")
        self.Version = QtWidgets.QLabel(self.Main)
        self.Version.setGeometry(QtCore.QRect(10, 470, 40, 10))
        self.Version.setObjectName("Version")
        self.Title = QtWidgets.QLabel(self.Main)
        self.Title.setGeometry(QtCore.QRect(160, 60, 280, 60))
        font = QtGui.QFont()
        font.setPointSize(34)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.OpenImage = QtWidgets.QPushButton(self.Main)
        self.OpenImage.setGeometry(QtCore.QRect(150, 350, 100, 40))
        self.OpenImage.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.OpenImage.setObjectName("OpenImage")
        self.Exit = QtWidgets.QPushButton(self.Main)
        self.Exit.setGeometry(QtCore.QRect(350, 350, 100, 40))
        self.Exit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Exit.setAutoDefault(False)
        self.Exit.setObjectName("Exit")
        self.label = QtWidgets.QLabel(self.Main)
        self.label.setGeometry(QtCore.QRect(100, 120, 400, 200))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Background = QtWidgets.QLabel(self.Main)
        self.Background.setGeometry(QtCore.QRect(0, 0, 600, 500))
        self.Background.setText("")
        self.Background.setPixmap(QtGui.QPixmap(":/Image/background.jpg"))
        self.Background.setScaledContents(True)
        self.Background.setObjectName("Background")
        self.CleanBackground = QtWidgets.QPushButton(self.Main)
        self.CleanBackground.setGeometry(QtCore.QRect(525, 480, 75, 20))
        self.CleanBackground.setStyleSheet("backgound-color:rgb(174, 196, 219)")
        self.CleanBackground.setObjectName("CleanBackground")
        self.Background.raise_()
        self.Author.raise_()
        self.Version.raise_()
        self.Title.raise_()
        self.OpenImage.raise_()
        self.Exit.raise_()
        self.label.raise_()
        self.CleanBackground.raise_()
        self.Wait = QtWidgets.QFrame(self.centralwidget)
        self.Wait.setGeometry(QtCore.QRect(0, 0, 600, 500))
        self.Wait.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Wait.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Wait.setObjectName("Wait")
        self.WaitText = QtWidgets.QLabel(self.Wait)
        self.WaitText.setGeometry(QtCore.QRect(300, 200, 290, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.WaitText.setFont(font)
        self.WaitText.setObjectName("WaitText")
        self.WaitIcon = QtWidgets.QLabel(self.Wait)
        self.WaitIcon.setGeometry(QtCore.QRect(100, 150, 200, 200))
        self.WaitIcon.setText("")
        self.WaitIcon.setPixmap(QtGui.QPixmap(":/WaitIcon/loading.gif"))
        self.WaitIcon.setObjectName("WaitIcon")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "口算批改程序"))
        self.Author.setText(_translate("MainWindow", "作者：ChenHaoYan"))
        self.Version.setText(_translate("MainWindow", "V1.0.0"))
        self.Title.setText(_translate("MainWindow", "口算批改程序"))
        self.OpenImage.setText(_translate("MainWindow", "打开图片"))
        self.Exit.setText(_translate("MainWindow", "退出"))
        self.label.setText(_translate("MainWindow", "请点击打开图片按钮以上传图片。"))
        self.CleanBackground.setText(_translate("MainWindow", "清除背景图片"))
        self.WaitText.setText(_translate("MainWindow", "正在识别中，坐和放宽。"))
import MainWindow_rc
